// @flow

export const COLORS = {
  Agouti: 'AGOUTI',
  Apricot: 'APRICOT',
  'Black Brindle': 'BL BRINDLE',
  Black: 'BLACK',
  'Black Smoke': 'BLK SMOKE',
  Blue: 'BLUE',
  'Blue Merle': 'BLUE MERLE',
  'Blue PT': 'BLUE PT',
  'Blue Tick': 'BLUE TICK',
  'Blue Tiger': 'BLUE TIGER',
  'Brown Brindle': 'BR BRINDLE',
  'Brown Merle': 'BRN MERLE',
  Brown: 'BROWN',
  Buff: 'BUFF',
  Chocolate: 'CHOCOLATE',
  Cream: 'CREAM',
  Fawn: 'FAWN',
  Gold: 'GOLD',
  Gray: 'GRAY',
  Green: 'GREEN',
  'Lilac PT': 'LILAC PT',
  Liver: 'LIVER',
  'Liver Tick': 'LIVER TICK',
  Orange: 'ORANGE',
  'Orange Tiger': 'ORANGE TIGER',
  Pink: 'PINK',
  Purple: 'PURPLE',
  Red: 'RED',
  'Red Merle': 'RED MERLE',
  'Red Tick': 'RED TICK',
  Muddle: 'MUDDLE',
  Sable: 'SABLE',
  'Seal PT': 'SEAL PT',
  Silver: 'SILVER',
  Tan: 'TAN',
  Tortie: 'TORTIE',
  Tricolor: 'TRICOLOR',
  White: 'WHITE',
  'Yellow Brindle': 'Y BRINDLE',
  Yellow: 'YELLOW',
};

export const NEIGHBORHOODS = {
  Allston: 'ALLSTON',
  'Back Bay': 'BACK BAY',
  'BEACON HILL': 'Beacon Hill',
  Boston: 'BOSTON',
  Brighton: 'BRIGHTON',
  Charleston: 'CHARLESTON',
  Dorchester: 'DORCHESTER',
  'East Boston': 'EAST BOSTON',
  'Hyde Park': 'HYDE PARK',
  'Jamaica Plain': 'JAMAICA PLAIN',
  Mattapan: 'MATTAPAN',
  Readville: 'READVILLE',
  Roslindale: 'ROSLINDALE',
  Roxbury: 'ROXBURY',
  'South Boston': 'SOUTH BOSTON',
  'West Roxbury': 'WEST ROXBURY',
};

export const BREEDS = {
  'Boykin Spaniel': 'BOYKIN SPAN',
  'Cairn Terrier': 'CAIRN TERRIER',
  'Bull Terrier': 'BULL TERRIER',
  Beauceron: 'BEAUCERON',
  'Belgian Malnois': 'BELG MALINOIS',
  'Ibizan Hound': 'IBIZAN HOUND',
  'French Bulldog': 'FRENCH BULLDOG',
  'Queensland Heel': 'QUEENSLAND HEEL',
  'German Shephard Point': 'GERM SH POINT',
  'Karelian Bear': 'KARELIAN BEAR',
  'English Bulldog': 'ENG BULLDOG',
  Landseer: 'LANDSEER',
  Vizla: 'VIZSLA',
  'Cocker Spaniel': 'COCKER SPAN',
  'Schnauzer (Miniature)': 'SCHNAUZER MIN',
  'Mexican Hairless': 'MEX HAIRLESS',
  'Italian Greyhound': 'ITAL GREYHOUND',
  'Portuguese Water Dog': 'PORT WATER DOG',
  'Sealyham Terrier': 'SEALYHAM TERR',
  'St. Bernard (SMTH)': 'ST BERNARD SMTH',
  'Plott Hound': 'PLOTT HOUND',
  Otterhound: 'OTTERHOUND',
  'Shetland Sheepdog': 'SHETLD SHEEPDOG',
  'Fox Terrier (Wire-haired)': 'FOX TERR WIRE',
  Briard: 'BRIARD',
  'Norwich Terrier': 'NORWICH TERRIER',
  Greyhound: 'GREYHOUND',
  'Cavalier Spaniel': 'CAVALIER SPAN',
  'German Shephard': 'GERM SHEPHERD',
  'Spanish Water Dog': 'SPAN WATER DOG',
  'Wire-haired Pointer Griffon': 'WH PT GRIFFON',
  'Lhasa Apso': 'LHASA APSO',
  'Manchester Terrier': 'MANCHESTER TERR',
  'Rat Terrier': 'RAT TERRIER',
  'Chesapeake Bay Retriever': 'CHESA BAY RETR',
  'Schnauzer (Giant)': 'SCHNAUZER GIANT',
  'Bluetick Hound': 'BLUETICK HOUND',
  Akita: 'AKITA',
  Harrier: 'HARRIER',
  'Pharoah Hound': 'PHARAOH HOUND',
  'American Bulldog': 'AMER BULLDOG',
  'Shiba Inu': 'SHIBA INU',
  'Gordon Setter': 'GORDON SETTER',
  'Collie (Smooth)': 'COLLIE SMOOTH',
  'American Eskimo': 'AMER ESKIMO',
  'English Springer Spaniel': 'ENG SPRNGR SPAN',
  Bullmastiff: 'BULLMASTIFF',
  Lowchen: 'LOWCHEN',
  'Italian Spinone': 'SPINONE ITAL',
  'Great Dane': 'GREAT DANE',
  'Bruss Griffon': 'BRUSS GRIFFON',
  Maltese: 'MALTESE',
  'West Highland': 'WEST HIGHLAND',
  'Treeing Walker Coonhound': 'TR WALKER HOUND',
  Tosa: 'TOSA',
  'American Foxhound': 'AMER FOXHOUND',
  'Tibetan Spaniel': 'TIBETAN SPAN',
  Papillion: 'PAPILLON',
  Ragdoll: 'RAGDOLL',
  'Old Enlish Bulldog': 'OLD ENG BULLDOG',
  Leonberger: 'LEONBERGER',
  'Greater Swiss Mountain': 'GR SWISS MTN',
  'Dutch Sheepdog': 'DUTCH SHEEPDOG',
  'Bichon Frise': 'BICHON FRISE',
  'Tibetan Mastiff': 'TIBETAN MASTIFF',
  Havanese: 'HAVANESE',
  'Mini Pinscher': 'MIN PINSCHER',
  Himalayan: 'HIMALAYAN',
  'Poodle (Standard)': 'POODLE STND',
  'Fox Terrier (Smooth)': 'FOX TERR SMOOTH',
  'Dogue de Bordeaux': 'DOGUE DE BORDX',
  'Labrador Retriever': 'LABRADOR RETR',
  'Nova Scotia Duck Tolling Retriever': 'NS DUCK TOLLING',
  'Belgian Tervuren': 'BELG TERVUREN',
  'Welsh Terrier': 'WELSH TERRIER',
  'Japanese Chin': 'JAPANESE CHIN',
  Hovaward: 'HOVAWART',
  'Irish Water Spaniel': 'IRISH WATR SPAN',
  'Hound (Black/Tan)': 'BLACK/TAN HOUND',
  Brittany: 'BRITTANY',
  'Silky Terrier': 'SILKY TERRIER',
  Staffordshire: 'STAFFORDSHIRE',
  'Siberian Husky': 'SIBERIAN HUSKY',
  'Chihuahua (Long-haired)': 'CHIHUAHUA LH',
  'Bull Terrier (Mini)': 'BULL TERR MIN',
  Rottweiler: 'ROTTWEILER',
  'American Staffordshire Terrier': 'AMERICAN STAFF',
  'Black Russian Terrier': 'BL RUSSIAN TER',
  Kuvasz: 'KUVASZ',
  'Kerry Blue Terrier': 'KERRY BLUE TERR',
  Basenji: 'BASENJI',
  'Pit Bull': 'PIT BULL',
  Pomeranian: 'POMERANIAN',
  'Sussex Spaniel': 'SUSSEX SPAN',
  Bat: 'BAT',
  'Alaskan Klee Kai': 'ALASK KLEE KAI',
  'Norweigan Elkhound': 'NORW ELKHOUND',
  Beagle: 'BEAGLE',
  'English Cocker Spaniel': 'ENG COCKER SPAN',
  'Poodle (Toy)': 'POODLE TOY',
  'English Pointer': 'ENG POINTER',
  'English Foxhound': 'ENG FOXHOUND',
  Siamese: 'SIAMESE',
  'Basset Hound': 'BASSET HOUND',
  'Irish Terrier': 'IRISH TERRIER',
  'Scottish Terrier': 'SCOT TERRIER',
  'Dachshund (Long-haired)': 'DACHSHUND LH',
  'Dutch Shepherd': 'DUTCH SHEPHERD',
  Borzoi: 'BORZOI',
  'American Shepherd': 'AMER SH',
  'Alaskan Husky': 'ALASKAN HUSKY',
  'Alaskan Malamute': 'ALASK MALAMUTE',
  'Belgian Sheepdog': 'BELG SHEEPDOG',
  'Soft Coated Wheaten Terrier': 'SC WHEAT TERR',
  'Irish Setter': 'IRISH SETTER',
  'English Setter': 'ENG SETTER',
  'Glen of Imaal Terrier': 'GLEN OF IMAAL',
  Komondor: 'KOMONDOR',
  'Poodle (Mini)': 'POODLE MIN',
  'Bedlington Terrier': 'BEDLINGTON TERR',
  'Bouvier Flandres': 'BOUV FLANDRES',
  'German Wire-haired Pointer': 'GERM WH POINT',
  'Field Spaniel': 'FIELD SPANIEL',
  'Chinese Crested': 'CHINESE CRESTED',
  'American Pit Bull Terrier': 'AM PIT BULL TER',
  Pug: 'PUG',
  Affenpinscher: 'AFFENPINSCHER',
  'Welsh Springer Spaniel': 'WELSH SPR SPAN',
  'Black Mouth Cur': 'BLACK MOUTH CUR',
  'Shih Tzu': 'SHIH TZU',
  Bulldog: 'BULLDOG',
  'Schnauzer (Standard)': 'SCHNAUZER STAND',
  Akbash: 'AKBASH',
  Feist: 'FEIST',
  Pointer: 'POINTER',
  'Swedish Vallhund': 'SWED VALLHUND',
  'English Toy Spaniel': 'ENG TOY SPANIEL',
  'Dachshund (Wire-haired)': 'DACHSHUND WH',
  'Patterdale Terrier': 'PATTERDALE TERR',
  'Redbone Hound': 'REDBONE HOUND',
  Bloodhound: 'BLOODHOUND',
  Boerboel: 'BOERBOEL',
  'English Coonhound': 'ENG COONHOUND',
  'Welsh Corgi (Cardigan)': 'WELSH CORGI CAR',
  'Polish Lowland': 'POLISH LOWLAND',
  Jindo: 'JINDO',
  'Swiss Hound': 'SWISS HOUND',
  'Lakeland Terrier': 'LAKELAND TERR',
  'Rhodesian Ridgeback': 'RHOD RIDGEBACK',
  'Border Collie': 'BORDER COLLIE',
  'Coton de Tulear': 'COTON DE TULEAR',
  'Fox Terrier (Toy)': 'TOY FOX TERRIER',
  'Airedale Terrier': 'AIREDALE TERR',
  'Scottish Deerhound': 'SCOT DEERHOUND',
  Saluki: 'SALUKI',
  'Flat Coat Retriever': 'FLAT COAT RETR',
  Samoyed: 'SAMOYED',
  Boxer: 'BOXER',
  'Carolina Dog': 'CAROLINA DOG',
  'Petit Basset Griffon Vendeen (PBGV)': 'PBGV',
  'Parson Russell Terrier': 'PARSON RUSS TER',
  'Grand Basset Griffon Vendeen (GBGV)': 'GBGV',
  'St. Bernard (RGH)': 'ST BERNARD RGH',
  'Norfolk Terrier': 'NORFOLK TERRIER',
  'Dachshund (Standard)': 'DACHSHUND',
  'English Shepherd': 'ENG SHEPHERD',
  'Treeing Cur': 'TREEING CUR',
  'Doberman Pinscher': 'DOBERMAN PINSCH',
  'Australian Terrier': 'AUST TERRIER',
  Mastiff: 'MASTIFF',
  'Australian Cattle Dog': 'AUST CATTLE DOG',
  'Golden Retriever': 'GOLDEN RETR',
  'Bernese Mountain Dog': 'BERNESE MTN DOG',
  Schipperke: 'SCHIPPERKE',
  'Finnish Spitz': 'FINNISH SPITZ',
  'Australian Shepherd': 'AUST SHEPHERD',
  'Irish Wolfhound': 'IRISH WOLFHOUND',
  'Border Terrier': 'BORDER TERRIER',
  'Afghan Hound': 'AFGHAN HOUND',
  'Bearded Collie': 'BEARDED COLLIE',
  Newfoundland: 'NEWFOUNDLAND',
  'Collie (Rough)': 'COLLIE ROUGH',
  'Treeing Tennessee Brindle': 'TENN TR BRINDLE',
  'Welsh Corgi (Pembroke)': 'WELSH CORGI PEM',
  Weimaraner: 'WEIMARANER',
  'German Pinscher': 'GERMAN PINSCHER',
  'Old English Sheepdog': 'OLDENG SHEEPDOG',
  Munsterlander: 'MUNSTERLANDER',
  'Dogo Argentino': 'DOGO ARGENTINO',
  Pekingese: 'PEKINGESE',
  'Yorkshire Terrier': 'YORKSHIRE TERR',
  'Australian Kelpie': 'AUST KELPIE',
  'Chihuahua (Short-haired)': 'CHIHUAHUA SH',
  'Curlycoat Retriever': 'CURLYCOAT RETR',
  Whippet: 'WHIPPET',
  'Norwegian Buhund': 'NORW BUHUND',
  'Clumber Spaniel': 'CLUMBER SPAN',
  'Presa Canario': 'PRESA CANARIO',
  Entlebucher: 'ENTLEBUCHER',
  'Neapolitan Mastiff': 'NEAPOLITAN MAST',
  Dalmatian: 'DALMATIAN',
  'Chinese Shar Pei': 'CHINESE SHARPEI',
  'Cane Corso': 'CANE CORSO',
  'Great Pyrenees': 'GREAT PYRENEES',
  'Chow Chow': 'CHOW CHOW',
  Keeshond: 'KEESHOND',
  'Boston Terrier': 'BOSTON TERRIER',
  'American Water Spaniel': 'AMER WATER SPAN',
  'Dandie Dinmont Terrier': 'DANDIE DINMONT',
  Catahoula: 'CATAHOULA',
  'Canaan Dog': 'CANAAN DOG',
  'Tibetan Terrier': 'TIBETAN TERR',
  Eurasier: 'EURASIER',
  'Portuguese Podengo (Pequeno)': 'PODENGO PEQUENO',
  Puli: 'PULI',
  'Anatolian Shepherd': 'ANATOL SHEPHERD',
};
